### ISSUE TITLE
Needs to be updated to the pin numbers on the breakout board

### ISSUE THREAD

**Issue by codekitty-jason-zz** [MnCode-CodeKitty/kitty-code#2]
@dmiracle did you keep pins D10 for the speaker and D12 for the tail?  what pin #s for the motors?

**Comment by dmiracle** [comment]
No I used arbitrary pins and messed up -- I thought the speaker was one of the analog outs. We will have to bodge the speaker connection to the correct pin. Easy to fix. I will update the pin #s

**Comment by codekitty-jason-zz** [comment]
Ack!  No worries.  I was using the tone() function for sound (
https://www.arduino.cc/en/Tutorial/ToneMelody?from=Tutorial.Tone).   We can
make it work :)

On Aug 4, 2017 7:43 AM, "dmiracle" <notifications@github.com> wrote:

No I used arbitrary pins and messed up -- I thought the speaker was one of
the analog outs. We will have to bodge the speaker connection to the
correct pin. Easy to fix. I will update the pin #s

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MnCode-CodeKitty/kitty-code/issues/2#issuecomment-320238981>,
or mute the thread

**Comment by dmiracle** [comment]
looks like analog pins can just be recast as digital pins, just not the other way around. Will update the library this weekend

**Comment by codekitty-jason-zz** [comment]
Awesome.  I was hoping for a simple solution :). So did the boards come?

**Comment by dmiracle** [comment]
Breakout Pins:
Left Servo   -- pin 12 -- D9
Right Servo -- pin 13 -- D10
Tail              -- pin 16 -- D13
Speaker       -- pin 19 -- A0

**Comment by dmiracle** [comment]
updated in breakout_mods branching. Marking resolved, we can merge in once that branch is working -- not ready to merge yet though!

**Comment by dmiracle** [comment]
boards will be in sometime next week

**Comment by codekitty-jason-zz** [comment]
That's great.  Thanks so much for taking care of this.   I am so excited
for this to all come together!
 I will send a status update email separately next.
